typography_spectrum: 0.7834268710575998
color:
  brandStrength: 0.19306101370602846
  lightness: 0.9827501927502453
  saturation: 0.896951649338007
  rhythmicContrast: 0.13712672400288284
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
layout_spectrum: 0.6873433066066355
name: Miri
title: Nirvana
description: Bliss
